/** Worker-only limits and TTLs. Changes here require Worker redeployment. */

const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
const BITS_PER_BYTE = 8;
const HEX_CHARS_PER_BYTE = 2;
const SHA256_BITS = 256;
const SHA256_DIGEST_BYTES = SHA256_BITS / BITS_PER_BYTE;
const TOKEN_VERSION = 1;

export const CRYPTO_CONFIG = {
  SHA256_DIGEST_BYTES,
  HEX_CHARS_PER_BYTE,
} as const;

export const PAIRING_CODE_TTL_SECONDS = SECONDS_PER_HOUR;
export const REGISTRATION_TTL_SECONDS = SECONDS_PER_HOUR;
export const PAIRING_CODE_LENGTH = 4;
export const PAIRING_CODE_PATTERN = new RegExp(`^[A-Za-z0-9]{${PAIRING_CODE_LENGTH}}$`);

export const TOKEN_CONFIG = {
  VERSION: TOKEN_VERSION,
  PREFIX: `v${TOKEN_VERSION}`,
  ALGORITHM: "PS256",
  TYPE: "CAST-CONNECTION",
  PURPOSE: "webtransport-connect",
  TIMESTAMP_SKEW_SECONDS: 5 * SECONDS_PER_MINUTE,
  REPLAY_TTL_SECONDS: 10 * SECONDS_PER_MINUTE,
  CONNECTION_TTL_SECONDS: SECONDS_PER_MINUTE,
  RSA_PSS_SALT_LENGTH: SHA256_DIGEST_BYTES,
  HMAC_SIGNATURE_BYTES: SHA256_DIGEST_BYTES,
  NONCE_MIN_BYTES: 8,
  NONCE_MAX_BYTES: 128,
} as const;

export const REQUEST_LIMITS = {
  MAX_BODY_BYTES: 16 * 1024,
  MAX_RECEIVER_ID_BYTES: 128,
  MIN_RECEIVER_SECRET_BYTES: SHA256_DIGEST_BYTES,
  CERTIFICATE_HASH_HEX_LENGTH: SHA256_DIGEST_BYTES * HEX_CHARS_PER_BYTE,
  TIMESTAMP_MAX_DIGITS: 12,
  RANDOM_NONCE_BYTES: 16,
} as const;

export const RATE_LIMITS = {
  PAIR_BY_IP: { MAX_REQUESTS: 10, WINDOW_SECONDS: SECONDS_PER_MINUTE },
  PAIR_BY_CODE: { MAX_REQUESTS: 5, WINDOW_SECONDS: SECONDS_PER_MINUTE },
  REGISTER_BY_IP: { MAX_REQUESTS: 20, WINDOW_SECONDS: SECONDS_PER_MINUTE },
  CLEANUP: { WINDOW_SECONDS: SECONDS_PER_HOUR },
} as const;

export const PAIRING_VALIDATION = {
  MIN_PORT: 1,
  MAX_PORT: (2 ** 16) - 1,
  RECEIVER_ID_PATTERN: new RegExp(`^[A-Za-z0-9_-]{1,${REQUEST_LIMITS.MAX_RECEIVER_ID_BYTES}}$`),
} as const;

export const BOOTSTRAP_LIMITS = {
  MAX_UI_BYTES: 2 * 1024 * 1024,
  CERTIFICATE_HASH_BYTES: SHA256_DIGEST_BYTES,
  LENGTH_PREFIX_BYTES: 4,
} as const;
