/** Worker-only limits and TTLs. Changes here require Worker redeployment. */

export const PAIRING_CODE_TTL_SECONDS = 3600;
export const REGISTRATION_TTL_SECONDS = 3600;
export const PAIRING_CODE_LENGTH = 4;
export const PAIRING_CODE_PATTERN = new RegExp(`^[A-Za-z0-9]{${PAIRING_CODE_LENGTH}}$`);

export const TOKEN_CONFIG = {
  TIMESTAMP_SKEW_SECONDS: 300,
  REPLAY_TTL_SECONDS: 600,
  CONNECTION_TTL_SECONDS: 60,
  RSA_PSS_SALT_LENGTH: 32,
  HMAC_SIGNATURE_BYTES: 32,
  NONCE_MIN_BYTES: 8,
  NONCE_MAX_BYTES: 128,
} as const;

export const REQUEST_LIMITS = {
  MAX_BODY_BYTES: 16 * 1024,
  MAX_RECEIVER_ID_BYTES: 128,
  MIN_RECEIVER_SECRET_BYTES: 32,
  CERTIFICATE_HASH_HEX_LENGTH: 64,
  TIMESTAMP_MAX_DIGITS: 12,
  RANDOM_NONCE_BYTES: 16,
} as const;

export const RATE_LIMITS = {
  PAIR_BY_IP: { MAX_REQUESTS: 10, WINDOW_SECONDS: 60 },
  PAIR_BY_CODE: { MAX_REQUESTS: 5, WINDOW_SECONDS: 60 },
  REGISTER_BY_IP: { MAX_REQUESTS: 20, WINDOW_SECONDS: 60 },
  CLEANUP: { WINDOW_SECONDS: 3600 },
} as const;

export const PAIRING_VALIDATION = {
  MIN_PORT: 1,
  MAX_PORT: 65_535,
  RECEIVER_ID_PATTERN: new RegExp(`^[A-Za-z0-9_-]{1,${REQUEST_LIMITS.MAX_RECEIVER_ID_BYTES}}$`),
} as const;

export const BOOTSTRAP_LIMITS = {
  MAX_UI_BYTES: 2 * 1024 * 1024,
  CERTIFICATE_HASH_BYTES: 32,
  FRAME_LENGTH_PREFIX_BYTES: 4,
} as const;
